
<Structures>
  <Structure Name="EntityList" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="Pointer" Bytesize="8" OffsetHex="00000000" DisplayMethod="unsigned integer"/>
      <Element Offset="8" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000008" DisplayMethod="unsigned integer"/>
      <Element Offset="16" Vartype="Pointer" Bytesize="8" OffsetHex="00000010" DisplayMethod="unsigned integer">
        <Structure Name="Autocreated from 1937A3E0148" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
          <Elements>
            <Element Offset="0" Vartype="Pointer" Bytesize="8" OffsetHex="00000000" Description="Pointer to instance of C_World" DisplayMethod="unsigned integer"/>
            <Element Offset="8" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="00000008" DisplayMethod="unsigned integer"/>
            <Element Offset="10" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000000A" DisplayMethod="unsigned integer"/>
            <Element Offset="12" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000000C" DisplayMethod="hexadecimal"/>
            <Element Offset="20" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000014" DisplayMethod="unsigned integer"/>
            <Element Offset="32" Vartype="Pointer" Bytesize="8" OffsetHex="00000020" DisplayMethod="unsigned integer"/>
            <Element Offset="40" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000028" DisplayMethod="unsigned integer"/>
            <Element Offset="64" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000040" DisplayMethod="hexadecimal"/>
            <Element Offset="68" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000044" DisplayMethod="unsigned integer"/>
            <Element Offset="88" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000058" DisplayMethod="unsigned integer"/>
            <Element Offset="104" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000068" DisplayMethod="unsigned integer"/>
            <Element Offset="120" Vartype="Pointer" Bytesize="8" OffsetHex="00000078" ChildStruct="PlayerController" Description="Pointer to instance of PlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="128" Vartype="Pointer" Bytesize="8" OffsetHex="00000080" DisplayMethod="unsigned integer"/>
            <Element Offset="136" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000088" DisplayMethod="hexadecimal"/>
            <Element Offset="140" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000008C" DisplayMethod="unsigned integer"/>
            <Element Offset="152" Vartype="Pointer" Bytesize="8" OffsetHex="00000098" DisplayMethod="unsigned integer"/>
            <Element Offset="160" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000000A0" DisplayMethod="unsigned integer"/>
            <Element Offset="184" Vartype="Float" Bytesize="4" OffsetHex="000000B8" DisplayMethod="unsigned integer"/>
            <Element Offset="188" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000BC" DisplayMethod="hexadecimal"/>
            <Element Offset="192" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000000C0" DisplayMethod="unsigned integer"/>
            <Element Offset="208" Vartype="Pointer" Bytesize="8" RLECount="3" OffsetHex="000000D0" DisplayMethod="unsigned integer"/>
            <Element Offset="232" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000E8" DisplayMethod="unsigned integer"/>
            <Element Offset="236" Vartype="Double" Bytesize="8" OffsetHex="000000EC" DisplayMethod="unsigned integer"/>
            <Element Offset="244" Vartype="4 Bytes" Bytesize="4" OffsetHex="000000F4" DisplayMethod="unsigned integer"/>
            <Element Offset="248" Vartype="Pointer" Bytesize="8" OffsetHex="000000F8" DisplayMethod="unsigned integer"/>
            <Element Offset="256" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000100" DisplayMethod="hexadecimal"/>
            <Element Offset="260" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000104" DisplayMethod="unsigned integer"/>
            <Element Offset="272" Vartype="Pointer" Bytesize="8" OffsetHex="00000110" DisplayMethod="unsigned integer"/>
            <Element Offset="280" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000118" DisplayMethod="unsigned integer"/>
            <Element Offset="304" Vartype="Float" Bytesize="4" OffsetHex="00000130" DisplayMethod="unsigned integer"/>
            <Element Offset="308" Vartype="String" Bytesize="5" OffsetHex="00000134" DisplayMethod="unsigned integer"/>
            <Element Offset="313" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000139" DisplayMethod="unsigned integer"/>
            <Element Offset="316" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000013C" DisplayMethod="unsigned integer"/>
            <Element Offset="328" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="00000148" DisplayMethod="unsigned integer"/>
            <Element Offset="360" Vartype="Pointer" Bytesize="8" OffsetHex="00000168" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="368" Vartype="Pointer" Bytesize="8" OffsetHex="00000170" DisplayMethod="unsigned integer"/>
            <Element Offset="376" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000178" DisplayMethod="hexadecimal"/>
            <Element Offset="380" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000017C" DisplayMethod="unsigned integer"/>
            <Element Offset="392" Vartype="Pointer" Bytesize="8" OffsetHex="00000188" DisplayMethod="unsigned integer"/>
            <Element Offset="400" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000190" DisplayMethod="unsigned integer"/>
            <Element Offset="424" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001A8" DisplayMethod="hexadecimal"/>
            <Element Offset="428" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="000001AC" DisplayMethod="unsigned integer"/>
            <Element Offset="448" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="000001C0" DisplayMethod="unsigned integer"/>
            <Element Offset="480" Vartype="Pointer" Bytesize="8" OffsetHex="000001E0" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="488" Vartype="Pointer" Bytesize="8" OffsetHex="000001E8" DisplayMethod="unsigned integer"/>
            <Element Offset="496" Vartype="4 Bytes" Bytesize="4" OffsetHex="000001F0" DisplayMethod="hexadecimal"/>
            <Element Offset="500" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000001F4" DisplayMethod="unsigned integer"/>
            <Element Offset="512" Vartype="Pointer" Bytesize="8" OffsetHex="00000200" DisplayMethod="unsigned integer"/>
            <Element Offset="520" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000208" DisplayMethod="unsigned integer"/>
            <Element Offset="544" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000220" DisplayMethod="hexadecimal"/>
            <Element Offset="548" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000224" DisplayMethod="unsigned integer"/>
            <Element Offset="568" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="00000238" DisplayMethod="unsigned integer"/>
            <Element Offset="600" Vartype="Pointer" Bytesize="8" OffsetHex="00000258" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="608" Vartype="Pointer" Bytesize="8" OffsetHex="00000260" DisplayMethod="unsigned integer"/>
            <Element Offset="616" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000268" DisplayMethod="hexadecimal"/>
            <Element Offset="620" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000026C" DisplayMethod="unsigned integer"/>
            <Element Offset="632" Vartype="Pointer" Bytesize="8" OffsetHex="00000278" DisplayMethod="unsigned integer"/>
            <Element Offset="640" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000280" DisplayMethod="unsigned integer"/>
            <Element Offset="664" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000298" DisplayMethod="hexadecimal"/>
            <Element Offset="668" Vartype="Float" Bytesize="4" OffsetHex="0000029C" DisplayMethod="unsigned integer"/>
            <Element Offset="672" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000002A0" DisplayMethod="unsigned integer"/>
            <Element Offset="688" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="000002B0" DisplayMethod="unsigned integer"/>
            <Element Offset="720" Vartype="Pointer" Bytesize="8" OffsetHex="000002D0" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="728" Vartype="Pointer" Bytesize="8" OffsetHex="000002D8" DisplayMethod="unsigned integer"/>
            <Element Offset="736" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002E0" DisplayMethod="hexadecimal"/>
            <Element Offset="740" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000002E4" DisplayMethod="unsigned integer"/>
            <Element Offset="752" Vartype="Pointer" Bytesize="8" OffsetHex="000002F0" DisplayMethod="unsigned integer"/>
            <Element Offset="760" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000002F8" DisplayMethod="unsigned integer"/>
            <Element Offset="784" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000310" DisplayMethod="hexadecimal"/>
            <Element Offset="792" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000318" DisplayMethod="unsigned integer"/>
            <Element Offset="808" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="00000328" DisplayMethod="unsigned integer"/>
            <Element Offset="840" Vartype="Pointer" Bytesize="8" OffsetHex="00000348" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="848" Vartype="Pointer" Bytesize="8" OffsetHex="00000350" DisplayMethod="unsigned integer"/>
            <Element Offset="856" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000358" DisplayMethod="hexadecimal"/>
            <Element Offset="860" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000035C" DisplayMethod="unsigned integer"/>
            <Element Offset="872" Vartype="Pointer" Bytesize="8" OffsetHex="00000368" DisplayMethod="unsigned integer"/>
            <Element Offset="880" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000370" DisplayMethod="unsigned integer"/>
            <Element Offset="904" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000388" DisplayMethod="hexadecimal"/>
            <Element Offset="912" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000390" DisplayMethod="unsigned integer"/>
            <Element Offset="928" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="000003A0" DisplayMethod="unsigned integer"/>
            <Element Offset="960" Vartype="Pointer" Bytesize="8" OffsetHex="000003C0" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="968" Vartype="Pointer" Bytesize="8" OffsetHex="000003C8" DisplayMethod="unsigned integer"/>
            <Element Offset="976" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003D0" DisplayMethod="hexadecimal"/>
            <Element Offset="980" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000003D4" DisplayMethod="unsigned integer"/>
            <Element Offset="992" Vartype="Pointer" Bytesize="8" OffsetHex="000003E0" DisplayMethod="unsigned integer"/>
            <Element Offset="1000" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000003E8" DisplayMethod="unsigned integer"/>
            <Element Offset="1024" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000400" DisplayMethod="hexadecimal"/>
            <Element Offset="1032" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000408" DisplayMethod="unsigned integer"/>
            <Element Offset="1048" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="00000418" DisplayMethod="unsigned integer"/>
            <Element Offset="1080" Vartype="Pointer" Bytesize="8" OffsetHex="00000438" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="1088" Vartype="Pointer" Bytesize="8" OffsetHex="00000440" DisplayMethod="unsigned integer"/>
            <Element Offset="1096" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000448" DisplayMethod="hexadecimal"/>
            <Element Offset="1100" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000044C" DisplayMethod="unsigned integer"/>
            <Element Offset="1112" Vartype="Pointer" Bytesize="8" OffsetHex="00000458" DisplayMethod="unsigned integer"/>
            <Element Offset="1120" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000460" DisplayMethod="unsigned integer"/>
            <Element Offset="1144" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000478" DisplayMethod="hexadecimal"/>
            <Element Offset="1152" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000480" DisplayMethod="unsigned integer"/>
            <Element Offset="1168" Vartype="Pointer" Bytesize="8" RLECount="4" OffsetHex="00000490" DisplayMethod="unsigned integer"/>
            <Element Offset="1200" Vartype="Pointer" Bytesize="8" OffsetHex="000004B0" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
            <Element Offset="1208" Vartype="Pointer" Bytesize="8" OffsetHex="000004B8" DisplayMethod="unsigned integer"/>
            <Element Offset="1216" Vartype="4 Bytes" Bytesize="4" OffsetHex="000004C0" DisplayMethod="hexadecimal"/>
            <Element Offset="1220" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000004C4" DisplayMethod="unsigned integer"/>
            <Element Offset="1232" Vartype="Pointer" Bytesize="8" OffsetHex="000004D0" DisplayMethod="unsigned integer"/>
            <Element Offset="1240" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000004D8" DisplayMethod="unsigned integer"/>
            <Element Offset="1264" Vartype="4 Bytes" Bytesize="4" OffsetHex="000004F0" DisplayMethod="hexadecimal"/>
            <Element Offset="1268" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="000004F4" DisplayMethod="unsigned integer"/>
            <Element Offset="1288" Vartype="Pointer" Bytesize="8" OffsetHex="00000508" DisplayMethod="unsigned integer"/>
            <Element Offset="1296" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000510" DisplayMethod="unsigned integer"/>
            <Element Offset="1300" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000514" DisplayMethod="unsigned integer"/>
            <Element Offset="1312" Vartype="Pointer" Bytesize="8" OffsetHex="00000520" DisplayMethod="unsigned integer"/>
            <Element Offset="1320" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000528" DisplayMethod="unsigned integer"/>
            <Element Offset="1336" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000538" DisplayMethod="hexadecimal"/>
            <Element Offset="1340" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="0000053C" DisplayMethod="unsigned integer"/>
            <Element Offset="1384" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000568" DisplayMethod="hexadecimal"/>
            <Element Offset="1392" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000570" DisplayMethod="unsigned integer"/>
            <Element Offset="1408" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000580" DisplayMethod="unsigned integer"/>
            <Element Offset="1412" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000584" DisplayMethod="unsigned integer"/>
            <Element Offset="1416" Vartype="Pointer" Bytesize="8" OffsetHex="00000588" DisplayMethod="unsigned integer"/>
            <Element Offset="1424" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000590" DisplayMethod="unsigned integer"/>
            <Element Offset="1456" Vartype="4 Bytes" Bytesize="4" OffsetHex="000005B0" DisplayMethod="hexadecimal"/>
            <Element Offset="1460" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="000005B4" DisplayMethod="unsigned integer"/>
            <Element Offset="1504" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000005E0" DisplayMethod="hexadecimal"/>
            <Element Offset="1512" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000005E8" DisplayMethod="unsigned integer"/>
            <Element Offset="1528" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000005F8" DisplayMethod="unsigned integer"/>
            <Element Offset="1544" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000608" DisplayMethod="unsigned integer"/>
            <Element Offset="1576" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000628" DisplayMethod="hexadecimal"/>
            <Element Offset="1580" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="0000062C" DisplayMethod="unsigned integer"/>
            <Element Offset="1624" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000658" DisplayMethod="hexadecimal"/>
            <Element Offset="1632" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000660" DisplayMethod="unsigned integer"/>
            <Element Offset="1648" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000670" DisplayMethod="unsigned integer"/>
            <Element Offset="1664" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000680" DisplayMethod="unsigned integer"/>
            <Element Offset="1696" Vartype="4 Bytes" Bytesize="4" OffsetHex="000006A0" DisplayMethod="hexadecimal"/>
            <Element Offset="1700" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="000006A4" DisplayMethod="unsigned integer"/>
            <Element Offset="1744" Vartype="4 Bytes" Bytesize="4" OffsetHex="000006D0" DisplayMethod="hexadecimal"/>
            <Element Offset="1748" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="000006D4" DisplayMethod="unsigned integer"/>
            <Element Offset="1776" Vartype="Pointer" Bytesize="8" OffsetHex="000006F0" DisplayMethod="unsigned integer"/>
            <Element Offset="1784" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000006F8" DisplayMethod="unsigned integer"/>
            <Element Offset="1816" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000718" DisplayMethod="hexadecimal"/>
            <Element Offset="1820" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="0000071C" DisplayMethod="unsigned integer"/>
            <Element Offset="1864" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000748" DisplayMethod="hexadecimal"/>
            <Element Offset="1868" Vartype="Float" Bytesize="4" OffsetHex="0000074C" DisplayMethod="unsigned integer"/>
            <Element Offset="1872" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000750" DisplayMethod="unsigned integer"/>
            <Element Offset="1888" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000760" DisplayMethod="unsigned integer"/>
            <Element Offset="1904" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000770" DisplayMethod="unsigned integer"/>
            <Element Offset="1936" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000790" DisplayMethod="hexadecimal"/>
            <Element Offset="1940" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000794" DisplayMethod="unsigned integer"/>
            <Element Offset="1984" Vartype="4 Bytes" Bytesize="4" OffsetHex="000007C0" DisplayMethod="hexadecimal"/>
            <Element Offset="1988" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="000007C4" DisplayMethod="unsigned integer"/>
            <Element Offset="1990" Vartype="2 Bytes" Bytesize="2" OffsetHex="000007C6" DisplayMethod="unsigned integer"/>
            <Element Offset="1992" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000007C8" DisplayMethod="unsigned integer"/>
            <Element Offset="2008" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000007D8" DisplayMethod="unsigned integer"/>
            <Element Offset="2024" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000007E8" DisplayMethod="unsigned integer"/>
            <Element Offset="2056" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000808" DisplayMethod="hexadecimal"/>
            <Element Offset="2060" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="0000080C" DisplayMethod="unsigned integer"/>
            <Element Offset="2104" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000838" DisplayMethod="hexadecimal"/>
            <Element Offset="2112" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000840" DisplayMethod="unsigned integer"/>
            <Element Offset="2128" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000850" DisplayMethod="unsigned integer"/>
            <Element Offset="2144" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000860" DisplayMethod="unsigned integer"/>
            <Element Offset="2176" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000880" DisplayMethod="hexadecimal"/>
            <Element Offset="2180" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000884" DisplayMethod="unsigned integer"/>
            <Element Offset="2224" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000008B0" DisplayMethod="hexadecimal"/>
            <Element Offset="2232" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000008B8" DisplayMethod="unsigned integer"/>
            <Element Offset="2248" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000008C8" DisplayMethod="unsigned integer"/>
            <Element Offset="2264" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000008D8" DisplayMethod="unsigned integer"/>
            <Element Offset="2296" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008F8" DisplayMethod="hexadecimal"/>
            <Element Offset="2300" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="000008FC" DisplayMethod="unsigned integer"/>
            <Element Offset="2344" Vartype="Float" Bytesize="4" OffsetHex="00000928" DisplayMethod="unsigned integer"/>
            <Element Offset="2348" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000092C" DisplayMethod="hexadecimal"/>
            <Element Offset="2352" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000930" DisplayMethod="unsigned integer"/>
            <Element Offset="2368" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000940" DisplayMethod="unsigned integer"/>
            <Element Offset="2384" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000950" DisplayMethod="unsigned integer"/>
            <Element Offset="2416" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000970" DisplayMethod="hexadecimal"/>
            <Element Offset="2420" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000974" DisplayMethod="unsigned integer"/>
            <Element Offset="2460" Vartype="Double" Bytesize="8" OffsetHex="0000099C" DisplayMethod="unsigned integer"/>
            <Element Offset="2468" Vartype="4 Bytes" Bytesize="4" OffsetHex="000009A4" DisplayMethod="hexadecimal"/>
            <Element Offset="2472" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000009A8" DisplayMethod="unsigned integer"/>
            <Element Offset="2488" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="000009B8" DisplayMethod="unsigned integer"/>
            <Element Offset="2504" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000009C8" DisplayMethod="unsigned integer"/>
            <Element Offset="2536" Vartype="Float" Bytesize="4" OffsetHex="000009E8" DisplayMethod="unsigned integer"/>
            <Element Offset="2540" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="000009EC" DisplayMethod="unsigned integer"/>
            <Element Offset="2584" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000A18" DisplayMethod="hexadecimal"/>
            <Element Offset="2592" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000A20" DisplayMethod="unsigned integer"/>
            <Element Offset="2608" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000A30" DisplayMethod="unsigned integer"/>
            <Element Offset="2624" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000A40" DisplayMethod="unsigned integer"/>
            <Element Offset="2656" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000A60" DisplayMethod="hexadecimal"/>
            <Element Offset="2660" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000A64" DisplayMethod="unsigned integer"/>
            <Element Offset="2704" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000A90" DisplayMethod="hexadecimal"/>
            <Element Offset="2708" Vartype="Float" Bytesize="4" OffsetHex="00000A94" DisplayMethod="unsigned integer"/>
            <Element Offset="2712" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000A98" DisplayMethod="unsigned integer"/>
            <Element Offset="2728" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000AA8" DisplayMethod="unsigned integer"/>
            <Element Offset="2744" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000AB8" DisplayMethod="unsigned integer"/>
            <Element Offset="2776" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AD8" DisplayMethod="hexadecimal"/>
            <Element Offset="2780" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000ADC" DisplayMethod="unsigned integer"/>
            <Element Offset="2824" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B08" DisplayMethod="hexadecimal"/>
            <Element Offset="2828" Vartype="String" Bytesize="5" OffsetHex="00000B0C" DisplayMethod="unsigned integer"/>
            <Element Offset="2833" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000B11" DisplayMethod="unsigned integer"/>
            <Element Offset="2836" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000B14" DisplayMethod="unsigned integer"/>
            <Element Offset="2848" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000B20" DisplayMethod="unsigned integer"/>
            <Element Offset="2864" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000B30" DisplayMethod="unsigned integer"/>
            <Element Offset="2896" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000B50" DisplayMethod="unsigned integer"/>
            <Element Offset="2900" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000B54" DisplayMethod="unsigned integer"/>
            <Element Offset="2944" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B80" DisplayMethod="hexadecimal"/>
            <Element Offset="2948" Vartype="String" Bytesize="5" OffsetHex="00000B84" DisplayMethod="unsigned integer"/>
            <Element Offset="2953" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000B89" DisplayMethod="unsigned integer"/>
            <Element Offset="2956" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000B8C" DisplayMethod="unsigned integer"/>
            <Element Offset="2968" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000B98" DisplayMethod="unsigned integer"/>
            <Element Offset="2984" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="00000BA8" DisplayMethod="unsigned integer"/>
            <Element Offset="3012" Vartype="Double" Bytesize="8" OffsetHex="00000BC4" DisplayMethod="unsigned integer"/>
            <Element Offset="3020" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000BCC" DisplayMethod="unsigned integer"/>
            <Element Offset="3064" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000BF8" DisplayMethod="hexadecimal"/>
            <Element Offset="3068" Vartype="String" Bytesize="5" OffsetHex="00000BFC" DisplayMethod="unsigned integer"/>
            <Element Offset="3073" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000C01" DisplayMethod="unsigned integer"/>
            <Element Offset="3076" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000C04" DisplayMethod="unsigned integer"/>
            <Element Offset="3088" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000C10" DisplayMethod="unsigned integer"/>
            <Element Offset="3104" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000C20" DisplayMethod="unsigned integer"/>
            <Element Offset="3136" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000C40" DisplayMethod="hexadecimal"/>
            <Element Offset="3140" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000C44" DisplayMethod="unsigned integer"/>
            <Element Offset="3184" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000C70" DisplayMethod="hexadecimal"/>
            <Element Offset="3192" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000C78" DisplayMethod="unsigned integer"/>
            <Element Offset="3208" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000C88" DisplayMethod="unsigned integer"/>
            <Element Offset="3224" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000C98" DisplayMethod="unsigned integer"/>
            <Element Offset="3256" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000CB8" DisplayMethod="hexadecimal"/>
            <Element Offset="3260" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000CBC" DisplayMethod="unsigned integer"/>
            <Element Offset="3304" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000CE8" DisplayMethod="hexadecimal"/>
            <Element Offset="3312" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000CF0" DisplayMethod="unsigned integer"/>
            <Element Offset="3328" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000D00" DisplayMethod="unsigned integer"/>
            <Element Offset="3344" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000D10" DisplayMethod="unsigned integer"/>
            <Element Offset="3376" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D30" DisplayMethod="hexadecimal"/>
            <Element Offset="3380" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000D34" DisplayMethod="unsigned integer"/>
            <Element Offset="3424" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000D60" DisplayMethod="hexadecimal"/>
            <Element Offset="3432" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000D68" DisplayMethod="unsigned integer"/>
            <Element Offset="3448" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000D78" DisplayMethod="unsigned integer"/>
            <Element Offset="3464" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000D88" DisplayMethod="unsigned integer"/>
            <Element Offset="3496" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000DA8" DisplayMethod="unsigned integer"/>
            <Element Offset="3500" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000DAC" DisplayMethod="unsigned integer"/>
            <Element Offset="3544" Vartype="Float" Bytesize="4" OffsetHex="00000DD8" DisplayMethod="unsigned integer"/>
            <Element Offset="3548" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DDC" DisplayMethod="hexadecimal"/>
            <Element Offset="3552" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000DE0" DisplayMethod="unsigned integer"/>
            <Element Offset="3568" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000DF0" DisplayMethod="unsigned integer"/>
            <Element Offset="3584" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="00000E00" DisplayMethod="unsigned integer"/>
            <Element Offset="3612" Vartype="Double" Bytesize="8" OffsetHex="00000E1C" DisplayMethod="unsigned integer"/>
            <Element Offset="3620" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000E24" DisplayMethod="unsigned integer"/>
            <Element Offset="3664" Vartype="Float" Bytesize="4" OffsetHex="00000E50" DisplayMethod="unsigned integer"/>
            <Element Offset="3668" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000E54" DisplayMethod="unsigned integer"/>
            <Element Offset="3672" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000E58" DisplayMethod="unsigned integer"/>
            <Element Offset="3688" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000E68" DisplayMethod="unsigned integer"/>
            <Element Offset="3704" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000E78" DisplayMethod="unsigned integer"/>
            <Element Offset="3736" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E98" DisplayMethod="hexadecimal"/>
            <Element Offset="3740" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000E9C" DisplayMethod="unsigned integer"/>
            <Element Offset="3784" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000EC8" DisplayMethod="hexadecimal"/>
            <Element Offset="3792" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000ED0" DisplayMethod="unsigned integer"/>
            <Element Offset="3808" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000EE0" DisplayMethod="unsigned integer"/>
            <Element Offset="3824" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000EF0" DisplayMethod="unsigned integer"/>
            <Element Offset="3856" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000F10" DisplayMethod="hexadecimal"/>
            <Element Offset="3860" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000F14" DisplayMethod="unsigned integer"/>
            <Element Offset="3904" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000F40" DisplayMethod="hexadecimal"/>
            <Element Offset="3912" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000F48" DisplayMethod="unsigned integer"/>
            <Element Offset="3928" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000F58" DisplayMethod="unsigned integer"/>
            <Element Offset="3944" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000F68" DisplayMethod="unsigned integer"/>
            <Element Offset="3976" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000F88" DisplayMethod="hexadecimal"/>
            <Element Offset="3980" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000F8C" DisplayMethod="unsigned integer"/>
            <Element Offset="4024" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000FB8" DisplayMethod="hexadecimal"/>
            <Element Offset="4028" Vartype="String" Bytesize="5" OffsetHex="00000FBC" DisplayMethod="unsigned integer"/>
            <Element Offset="4033" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000FC1" DisplayMethod="unsigned integer"/>
            <Element Offset="4036" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000FC4" DisplayMethod="unsigned integer"/>
            <Element Offset="4048" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000FD0" DisplayMethod="unsigned integer"/>
            <Element Offset="4064" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000FE0" DisplayMethod="unsigned integer"/>
          </Elements>
        </Structure>
      </Element>
      <Element Offset="24" Vartype="4 Bytes" Bytesize="4" RLECount="62" OffsetHex="00000018" DisplayMethod="unsigned integer"/>
      <Element Offset="272" Vartype="Pointer" Bytesize="8" OffsetHex="00000110" DisplayMethod="unsigned integer"/>
      <Element Offset="280" Vartype="4 Bytes" Bytesize="4" RLECount="62" OffsetHex="00000118" DisplayMethod="unsigned integer"/>
      <Element Offset="528" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000210" DisplayMethod="unsigned integer"/>
      <Element Offset="544" Vartype="String" Bytesize="4" OffsetHex="00000220" DisplayMethod="unsigned integer"/>
      <Element Offset="548" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000224" DisplayMethod="unsigned integer"/>
      <Element Offset="560" Vartype="String" Bytesize="4" OffsetHex="00000230" DisplayMethod="unsigned integer"/>
      <Element Offset="564" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000234" DisplayMethod="unsigned integer"/>
      <Element Offset="568" Vartype="String" Bytesize="4" OffsetHex="00000238" DisplayMethod="unsigned integer"/>
      <Element Offset="572" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000023C" DisplayMethod="unsigned integer"/>
      <Element Offset="584" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000248" DisplayMethod="unsigned integer"/>
      <Element Offset="600" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000258" DisplayMethod="unsigned integer"/>
      <Element Offset="608" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000260" DisplayMethod="unsigned integer"/>
      <Element Offset="624" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000270" DisplayMethod="unsigned integer"/>
      <Element Offset="632" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000278" DisplayMethod="hexadecimal"/>
      <Element Offset="640" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000280" DisplayMethod="unsigned integer"/>
      <Element Offset="652" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000028C" DisplayMethod="hexadecimal"/>
      <Element Offset="664" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000298" DisplayMethod="unsigned integer"/>
      <Element Offset="668" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="0000029C" DisplayMethod="hexadecimal"/>
      <Element Offset="700" Vartype="Double" Bytesize="8" OffsetHex="000002BC" DisplayMethod="unsigned integer"/>
      <Element Offset="708" Vartype="4 Bytes" Bytesize="4" RLECount="497" OffsetHex="000002C4" DisplayMethod="unsigned integer"/>
      <Element Offset="2696" Vartype="Pointer" Bytesize="8" OffsetHex="00000A88" DisplayMethod="unsigned integer"/>
      <Element Offset="2704" Vartype="String" Bytesize="4" OffsetHex="00000A90" DisplayMethod="unsigned integer"/>
      <Element Offset="2708" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000A94" DisplayMethod="hexadecimal"/>
      <Element Offset="2712" Vartype="Pointer" Bytesize="8" OffsetHex="00000A98" DisplayMethod="unsigned integer"/>
      <Element Offset="2720" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AA0" DisplayMethod="unsigned integer"/>
      <Element Offset="2728" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AA8" DisplayMethod="hexadecimal"/>
      <Element Offset="2736" Vartype="String" Bytesize="4" OffsetHex="00000AB0" DisplayMethod="unsigned integer"/>
      <Element Offset="2740" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AB4" DisplayMethod="hexadecimal"/>
      <Element Offset="2744" Vartype="Pointer" Bytesize="8" OffsetHex="00000AB8" DisplayMethod="unsigned integer"/>
      <Element Offset="2752" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AC0" DisplayMethod="unsigned integer"/>
      <Element Offset="2760" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AC8" DisplayMethod="hexadecimal"/>
      <Element Offset="2768" Vartype="String" Bytesize="4" OffsetHex="00000AD0" DisplayMethod="unsigned integer"/>
      <Element Offset="2772" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000AD4" DisplayMethod="hexadecimal"/>
      <Element Offset="2776" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000AD8" DisplayMethod="unsigned integer"/>
      <Element Offset="2780" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000ADC" DisplayMethod="unsigned integer"/>
      <Element Offset="2792" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000AE8" DisplayMethod="hexadecimal"/>
      <Element Offset="2800" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000AF0" DisplayMethod="unsigned integer"/>
      <Element Offset="2816" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000B00" DisplayMethod="unsigned integer"/>
      <Element Offset="2824" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000B08" DisplayMethod="hexadecimal"/>
      <Element Offset="2832" Vartype="4 Bytes" Bytesize="4" RLECount="14" OffsetHex="00000B10" DisplayMethod="unsigned integer"/>
      <Element Offset="2888" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B48" DisplayMethod="hexadecimal"/>
      <Element Offset="2892" Vartype="4 Bytes" Bytesize="4" RLECount="21" OffsetHex="00000B4C" DisplayMethod="unsigned integer"/>
      <Element Offset="2976" Vartype="Pointer" Bytesize="8" OffsetHex="00000BA0" DisplayMethod="unsigned integer"/>
      <Element Offset="2984" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000BA8" DisplayMethod="unsigned integer"/>
      <Element Offset="2988" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000BAC" DisplayMethod="hexadecimal"/>
      <Element Offset="2992" Vartype="Pointer" Bytesize="8" OffsetHex="00000BB0" Description="Pointer to instance of CEntityIONotify" DisplayMethod="unsigned integer"/>
      <Element Offset="3000" Vartype="Pointer" Bytesize="8" OffsetHex="00000BB8" Description="Pointer to instance of CDebugOverlayEntityBrowser" DisplayMethod="unsigned integer"/>
      <Element Offset="3008" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000BC0" DisplayMethod="unsigned integer"/>
      <Element Offset="3040" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000BE0" DisplayMethod="hexadecimal"/>
      <Element Offset="3044" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000BE4" DisplayMethod="unsigned integer"/>
      <Element Offset="3056" Vartype="Float" Bytesize="4" OffsetHex="00000BF0" DisplayMethod="unsigned integer"/>
      <Element Offset="3060" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000BF4" DisplayMethod="unsigned integer"/>
      <Element Offset="3080" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000C08" DisplayMethod="unsigned integer"/>
      <Element Offset="3084" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000C0C" DisplayMethod="unsigned integer"/>
      <Element Offset="3104" Vartype="Pointer" Bytesize="8" OffsetHex="00000C20" DisplayMethod="unsigned integer"/>
      <Element Offset="3112" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000C28" DisplayMethod="unsigned integer"/>
      <Element Offset="3152" Vartype="Pointer" Bytesize="8" OffsetHex="00000C50" DisplayMethod="unsigned integer"/>
      <Element Offset="3160" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000C58" DisplayMethod="unsigned integer"/>
      <Element Offset="3208" Vartype="Pointer" Bytesize="8" OffsetHex="00000C88" Description="Pointer to instance of CNetworkFieldChangedEventQueue" DisplayMethod="unsigned integer"/>
      <Element Offset="3216" Vartype="Pointer" Bytesize="8" OffsetHex="00000C90" Description="Pointer to instance of CNetworkFieldScratchData" DisplayMethod="unsigned integer"/>
      <Element Offset="3224" Vartype="Pointer" Bytesize="8" OffsetHex="00000C98" Description="Pointer to instance of CSource2Client" DisplayMethod="unsigned integer"/>
      <Element Offset="3232" Vartype="Pointer" Bytesize="8" OffsetHex="00000CA0" DisplayMethod="unsigned integer"/>
      <Element Offset="3240" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000CA8" DisplayMethod="unsigned integer"/>
      <Element Offset="3264" Vartype="Pointer" Bytesize="8" OffsetHex="00000CC0" DisplayMethod="unsigned integer"/>
      <Element Offset="3272" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000CC8" DisplayMethod="unsigned integer"/>
      <Element Offset="3280" Vartype="Pointer" Bytesize="8" OffsetHex="00000CD0" DisplayMethod="unsigned integer"/>
      <Element Offset="3288" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000CD8" DisplayMethod="unsigned integer"/>
      <Element Offset="3328" Vartype="Pointer" Bytesize="8" OffsetHex="00000D00" DisplayMethod="unsigned integer"/>
      <Element Offset="3336" Vartype="String" Bytesize="4" OffsetHex="00000D08" DisplayMethod="unsigned integer"/>
      <Element Offset="3340" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D0C" DisplayMethod="hexadecimal"/>
      <Element Offset="3344" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000D10" DisplayMethod="unsigned integer"/>
      <Element Offset="3352" Vartype="Pointer" Bytesize="8" OffsetHex="00000D18" DisplayMethod="unsigned integer"/>
      <Element Offset="3360" Vartype="4 Bytes" Bytesize="4" RLECount="184" OffsetHex="00000D20" DisplayMethod="unsigned integer"/>
    </Elements>
  </Structure>
  <Structure Name="PlayerController" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="Pointer" Bytesize="8" OffsetHex="00000000" DisplayMethod="unsigned integer">
        <Structure Name="Autocreated from 7FFA26D2E340" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
          <Elements>
            <Element Offset="0" Vartype="Pointer" Bytesize="8" RLECount="136" OffsetHex="00000000" DisplayMethod="unsigned integer"/>
            <Element Offset="1088" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000440" DisplayMethod="unsigned integer"/>
            <Element Offset="1092" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000444" DisplayMethod="hexadecimal"/>
            <Element Offset="1096" Vartype="Pointer" Bytesize="8" RLECount="44" OffsetHex="00000448" DisplayMethod="unsigned integer"/>
            <Element Offset="1448" Vartype="String" Bytesize="4" OffsetHex="000005A8" DisplayMethod="unsigned integer"/>
            <Element Offset="1452" Vartype="4 Bytes" Bytesize="4" OffsetHex="000005AC" DisplayMethod="hexadecimal"/>
            <Element Offset="1456" Vartype="Pointer" Bytesize="8" RLECount="94" OffsetHex="000005B0" DisplayMethod="unsigned integer"/>
            <Element Offset="2208" Vartype="Float" Bytesize="4" RLECount="3" OffsetHex="000008A0" DisplayMethod="unsigned integer"/>
            <Element Offset="2220" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008AC" DisplayMethod="unsigned integer"/>
            <Element Offset="2224" Vartype="Float" Bytesize="4" RLECount="3" OffsetHex="000008B0" DisplayMethod="unsigned integer"/>
            <Element Offset="2236" Vartype="String" Bytesize="7" OffsetHex="000008BC" DisplayMethod="unsigned integer"/>
            <Element Offset="2243" Vartype="Byte" Bytesize="1" OffsetHex="000008C3" DisplayMethod="unsigned integer"/>
            <Element Offset="2244" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008C4" DisplayMethod="unsigned integer"/>
            <Element Offset="2248" Vartype="Pointer" Bytesize="8" RLECount="134" OffsetHex="000008C8" DisplayMethod="unsigned integer"/>
            <Element Offset="3320" Vartype="String" Bytesize="4" OffsetHex="00000CF8" DisplayMethod="unsigned integer"/>
            <Element Offset="3324" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000CFC" DisplayMethod="hexadecimal"/>
            <Element Offset="3328" Vartype="Pointer" Bytesize="8" RLECount="2" OffsetHex="00000D00" DisplayMethod="unsigned integer"/>
            <Element Offset="3344" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="00000D10" DisplayMethod="unsigned integer"/>
            <Element Offset="3348" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D14" DisplayMethod="hexadecimal"/>
            <Element Offset="3352" Vartype="Pointer" Bytesize="8" RLECount="44" OffsetHex="00000D18" DisplayMethod="unsigned integer"/>
            <Element Offset="3704" Vartype="String" Bytesize="4" OffsetHex="00000E78" DisplayMethod="unsigned integer"/>
            <Element Offset="3708" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E7C" DisplayMethod="hexadecimal"/>
            <Element Offset="3712" Vartype="Pointer" Bytesize="8" RLECount="48" OffsetHex="00000E80" DisplayMethod="unsigned integer"/>
          </Elements>
        </Structure>
      </Element>
      <Element Offset="8" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000008" DisplayMethod="unsigned integer"/>
      <Element Offset="16" Vartype="Pointer" Bytesize="8" OffsetHex="00000010" DisplayMethod="unsigned integer"/>
      <Element Offset="24" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000018" DisplayMethod="unsigned integer"/>
      <Element Offset="48" Vartype="Pointer" Bytesize="8" OffsetHex="00000030" Description="Pointer to instance of CBodyComponentPoint" DisplayMethod="unsigned integer"/>
      <Element Offset="56" Vartype="Pointer" Bytesize="8" OffsetHex="00000038" DisplayMethod="unsigned integer"/>
      <Element Offset="64" Vartype="4 Bytes" Bytesize="4" RLECount="73" OffsetHex="00000040" DisplayMethod="unsigned integer"/>
      <Element Offset="356" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000164" DisplayMethod="hexadecimal"/>
      <Element Offset="364" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000016C" DisplayMethod="unsigned integer"/>
      <Element Offset="376" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000178" DisplayMethod="hexadecimal"/>
      <Element Offset="380" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000017C" DisplayMethod="unsigned integer"/>
      <Element Offset="392" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000188" DisplayMethod="hexadecimal"/>
      <Element Offset="396" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="0000018C" DisplayMethod="unsigned integer"/>
      <Element Offset="424" Vartype="Pointer" Bytesize="8" OffsetHex="000001A8" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
      <Element Offset="432" Vartype="4 Bytes" Bytesize="4" RLECount="14" OffsetHex="000001B0" DisplayMethod="unsigned integer"/>
      <Element Offset="488" Vartype="Pointer" Bytesize="8" OffsetHex="000001E8" DisplayMethod="unsigned integer"/>
      <Element Offset="496" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="000001F0" DisplayMethod="unsigned integer"/>
      <Element Offset="544" Vartype="Float" Bytesize="4" OffsetHex="00000220" DisplayMethod="unsigned integer"/>
      <Element Offset="548" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000224" DisplayMethod="unsigned integer"/>
      <Element Offset="552" Vartype="Float" Bytesize="4" OffsetHex="00000228" DisplayMethod="unsigned integer"/>
      <Element Offset="556" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="0000022C" DisplayMethod="unsigned integer"/>
      <Element Offset="576" Vartype="Pointer" Bytesize="8" OffsetHex="00000240" DisplayMethod="unsigned integer"/>
      <Element Offset="584" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000248" DisplayMethod="unsigned integer"/>
      <Element Offset="600" Vartype="Pointer" Bytesize="8" OffsetHex="00000258" DisplayMethod="unsigned integer"/>
      <Element Offset="608" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000260" DisplayMethod="unsigned integer"/>
      <Element Offset="616" Vartype="Float" Bytesize="4" OffsetHex="00000268" DisplayMethod="unsigned integer"/>
      <Element Offset="620" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000026C" DisplayMethod="unsigned integer"/>
      <Element Offset="624" Vartype="Float" Bytesize="4" OffsetHex="00000270" DisplayMethod="unsigned integer"/>
      <Element Offset="628" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000274" DisplayMethod="unsigned integer"/>
      <Element Offset="648" Vartype="Pointer" Bytesize="8" OffsetHex="00000288" DisplayMethod="unsigned integer"/>
      <Element Offset="656" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000290" DisplayMethod="unsigned integer"/>
      <Element Offset="688" Vartype="Float" Bytesize="4" OffsetHex="000002B0" DisplayMethod="unsigned integer"/>
      <Element Offset="692" Vartype="4 Bytes" Bytesize="4" OffsetHex="000002B4" DisplayMethod="unsigned integer"/>
      <Element Offset="696" Vartype="Float" Bytesize="4" OffsetHex="000002B8" DisplayMethod="unsigned integer"/>
      <Element Offset="700" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="000002BC" DisplayMethod="unsigned integer"/>
      <Element Offset="728" Vartype="Pointer" Bytesize="8" OffsetHex="000002D8" DisplayMethod="unsigned integer"/>
      <Element Offset="736" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000002E0" DisplayMethod="unsigned integer"/>
      <Element Offset="744" Vartype="Pointer" Bytesize="8" OffsetHex="000002E8" DisplayMethod="unsigned integer"/>
      <Element Offset="752" Vartype="Pointer" Bytesize="8" OffsetHex="000002F0" Description="Pointer to instance of CCSPlayerController" DisplayMethod="unsigned integer"/>
      <Element Offset="760" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="000002F8" DisplayMethod="unsigned integer"/>
      <Element Offset="784" Vartype="Pointer" Bytesize="8" OffsetHex="00000310" Description="Pointer to instance of CBodyComponentPoint::NetworkVar_m_sceneNode" DisplayMethod="unsigned integer"/>
      <Element Offset="792" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000318" DisplayMethod="unsigned integer"/>
      <Element Offset="836" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000344" DisplayMethod="unsigned integer"/>
      <Element Offset="844" Vartype="4 Bytes" Bytesize="4" OffsetHex="0000034C" DisplayMethod="unsigned integer"/>
      <Element Offset="848" Vartype="Pointer" Bytesize="8" OffsetHex="00000350" DisplayMethod="unsigned integer"/>
      <Element Offset="856" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000358" DisplayMethod="unsigned integer"/>
      <Element Offset="872" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000368" DisplayMethod="hexadecimal"/>
      <Element Offset="876" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="0000036C" DisplayMethod="unsigned integer"/>
      <Element Offset="908" Vartype="Float" Bytesize="4" OffsetHex="0000038C" DisplayMethod="unsigned integer"/>
      <Element Offset="912" Vartype="Pointer" Bytesize="8" OffsetHex="00000390" DisplayMethod="unsigned integer"/>
      <Element Offset="920" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000398" DisplayMethod="unsigned integer"/>
      <Element Offset="944" Vartype="Double" Bytesize="8" OffsetHex="000003B0" DisplayMethod="unsigned integer"/>
      <Element Offset="952" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003B8" DisplayMethod="unsigned integer"/>
      <Element Offset="959" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003BF" Description="TeamNumber" DisplayMethod="unsigned integer"/>
      <Element Offset="960" Vartype="4 Bytes" Bytesize="4" RLECount="9" OffsetHex="000003C0" DisplayMethod="unsigned integer"/>
      <Element Offset="996" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003E4" DisplayMethod="hexadecimal"/>
      <Element Offset="1000" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003E8" DisplayMethod="unsigned integer"/>
      <Element Offset="1004" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003EC" DisplayMethod="hexadecimal"/>
      <Element Offset="1008" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003F0" DisplayMethod="unsigned integer"/>
      <Element Offset="1012" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003F4" DisplayMethod="hexadecimal"/>
      <Element Offset="1016" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003F8" DisplayMethod="unsigned integer"/>
      <Element Offset="1020" Vartype="4 Bytes" Bytesize="4" OffsetHex="000003FC" DisplayMethod="hexadecimal"/>
      <Element Offset="1024" Vartype="Pointer" Bytesize="8" OffsetHex="00000400" Description="Pointer to instance of CWrappedInterpolatedVarGuts&lt;CNetworkVelocityVector,1,CNetworkVelocityVector,0,CInterpolatedVar&lt;CNetworkVelocityVector&gt; &gt;" DisplayMethod="unsigned integer"/>
      <Element Offset="1032" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000408" DisplayMethod="unsigned integer"/>
      <Element Offset="1064" Vartype="Float" Bytesize="4" RLECount="2" OffsetHex="00000428" DisplayMethod="unsigned integer"/>
      <Element Offset="1072" Vartype="Double" Bytesize="8" OffsetHex="00000430" DisplayMethod="unsigned integer"/>
      <Element Offset="1080" Vartype="Float" Bytesize="4" OffsetHex="00000438" DisplayMethod="unsigned integer"/>
      <Element Offset="1084" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="0000043C" DisplayMethod="unsigned integer"/>
      <Element Offset="1092" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000444" DisplayMethod="hexadecimal"/>
      <Element Offset="1096" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000448" DisplayMethod="unsigned integer"/>
      <Element Offset="1128" Vartype="Pointer" Bytesize="8" OffsetHex="00000468" Description="Pointer to instance of CParticleMgr" DisplayMethod="unsigned integer"/>
      <Element Offset="1136" Vartype="Pointer" Bytesize="8" OffsetHex="00000470" Description="Pointer to instance of C_BaseEntityOuterHelper" DisplayMethod="unsigned integer"/>
      <Element Offset="1144" Vartype="4 Bytes" Bytesize="4" RLECount="26" OffsetHex="00000478" DisplayMethod="unsigned integer"/>
      <Element Offset="1248" Vartype="Pointer" Bytesize="8" OffsetHex="000004E0" DisplayMethod="unsigned integer"/>
      <Element Offset="1256" Vartype="4 Bytes" Bytesize="4" RLECount="22" OffsetHex="000004E8" DisplayMethod="unsigned integer"/>
      <Element Offset="1344" Vartype="Pointer" Bytesize="8" OffsetHex="00000540" Description="Pointer to instance of CCSPlayerController_InGameMoneyServices" DisplayMethod="unsigned integer"/>
      <Element Offset="1352" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000548" DisplayMethod="hexadecimal"/>
      <Element Offset="1356" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="0000054C" DisplayMethod="unsigned integer"/>
      <Element Offset="1368" Vartype="Pointer" Bytesize="8" OffsetHex="00000558" DisplayMethod="unsigned integer"/>
      <Element Offset="1376" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000560" DisplayMethod="unsigned integer"/>
      <Element Offset="1408" Vartype="Pointer" Bytesize="8" OffsetHex="00000580" DisplayMethod="unsigned integer"/>
      <Element Offset="1416" Vartype="Pointer" Bytesize="8" OffsetHex="00000588" Description="Pointer to instance of CBaseUserCmdPB" DisplayMethod="unsigned integer"/>
      <Element Offset="1424" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000590" DisplayMethod="unsigned integer"/>
      <Element Offset="1448" Vartype="Pointer" Bytesize="8" OffsetHex="000005A8" DisplayMethod="unsigned integer"/>
      <Element Offset="1456" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000005B0" DisplayMethod="unsigned integer"/>
      <Element Offset="1488" Vartype="Double" Bytesize="8" OffsetHex="000005D0" DisplayMethod="unsigned integer"/>
      <Element Offset="1496" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="000005D8" DisplayMethod="unsigned integer"/>
      <Element Offset="1528" Vartype="4 Bytes" Bytesize="4" OffsetHex="000005F8" DisplayMethod="hexadecimal"/>
      <Element Offset="1532" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000005FC" DisplayMethod="unsigned integer"/>
      <Element Offset="1544" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000608" DisplayMethod="hexadecimal"/>
      <Element Offset="1556" Vartype="4 Bytes" Bytesize="4" RLECount="11" OffsetHex="00000614" DisplayMethod="unsigned integer"/>
      <Element Offset="1600" Vartype="String" Bytesize="9" OffsetHex="00000640" DisplayMethod="unsigned integer"/>
      <Element Offset="1609" Vartype="Byte" Bytesize="1" RLECount="3" OffsetHex="00000649" DisplayMethod="unsigned integer"/>
      <Element Offset="1612" Vartype="4 Bytes" Bytesize="4" RLECount="31" OffsetHex="0000064C" DisplayMethod="unsigned integer"/>
      <Element Offset="1736" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000006C8" DisplayMethod="hexadecimal"/>
      <Element Offset="1744" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="000006D0" DisplayMethod="unsigned integer"/>
      <Element Offset="1760" Vartype="Pointer" Bytesize="8" OffsetHex="000006E0" DisplayMethod="unsigned integer"/>
      <Element Offset="1768" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000006E8" DisplayMethod="unsigned integer"/>
      <Element Offset="1776" Vartype="Pointer" Bytesize="8" OffsetHex="000006F0" DisplayMethod="unsigned integer"/>
      <Element Offset="1784" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="000006F8" DisplayMethod="unsigned integer"/>
      <Element Offset="1792" Vartype="Pointer" Bytesize="8" OffsetHex="00000700" Description="Pointer to instance of CCSPlayerController_InGameMoneyServices" DisplayMethod="unsigned integer"/>
      <Element Offset="1800" Vartype="Pointer" Bytesize="8" OffsetHex="00000708" Description="Pointer to instance of CCSPlayerController_InventoryServices" DisplayMethod="unsigned integer"/>
      <Element Offset="1808" Vartype="Pointer" Bytesize="8" OffsetHex="00000710" Description="Pointer to instance of CCSPlayerController_ActionTrackingServices" DisplayMethod="unsigned integer"/>
      <Element Offset="1816" Vartype="Pointer" Bytesize="8" OffsetHex="00000718" Description="Pointer to instance of CCSPlayerController_DamageServices" DisplayMethod="unsigned integer"/>
      <Element Offset="1824" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000720" DisplayMethod="unsigned integer"/>
      <Element Offset="1832" Vartype="Pointer" Bytesize="8" OffsetHex="00000728" DisplayMethod="unsigned integer"/>
      <Element Offset="1840" Vartype="Double" Bytesize="8" OffsetHex="00000730" DisplayMethod="unsigned integer"/>
      <Element Offset="1848" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000738" DisplayMethod="unsigned integer"/>
      <Element Offset="1852" Vartype="Double" Bytesize="8" OffsetHex="0000073C" DisplayMethod="unsigned integer"/>
      <Element Offset="1860" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000744" DisplayMethod="unsigned integer"/>
      <Element Offset="1872" Vartype="Pointer" Bytesize="8" OffsetHex="00000750" DisplayMethod="unsigned integer"/>
      <Element Offset="1880" Vartype="4 Bytes" Bytesize="4" RLECount="37" OffsetHex="00000758" DisplayMethod="unsigned integer"/>
      <Element Offset="2028" Vartype="4 Bytes" Bytesize="4" OffsetHex="000007EC" Description="PawnHandle" DisplayMethod="hexadecimal"/>
      <Element Offset="2032" Vartype="4 Bytes" Bytesize="4" OffsetHex="000007F0" DisplayMethod="hexadecimal"/>
      <Element Offset="2036" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000007F4" DisplayMethod="unsigned integer"/>
      <Element Offset="2048" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000800" DisplayMethod="hexadecimal"/>
      <Element Offset="2056" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000808" DisplayMethod="unsigned integer"/>
      <Element Offset="2064" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000810" DisplayMethod="hexadecimal"/>
      <Element Offset="2068" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000814" DisplayMethod="unsigned integer"/>
      <Element Offset="2080" Vartype="Pointer" Bytesize="8" OffsetHex="00000820" DisplayMethod="unsigned integer"/>
      <Element Offset="2088" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000828" DisplayMethod="unsigned integer"/>
      <Element Offset="2112" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000840" DisplayMethod="hexadecimal"/>
      <Element Offset="2116" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000844" DisplayMethod="unsigned integer"/>
      <Element Offset="2128" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000850" DisplayMethod="hexadecimal"/>
      <Element Offset="2132" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000854" DisplayMethod="unsigned integer"/>
      <Element Offset="2144" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000860" DisplayMethod="hexadecimal"/>
      <Element Offset="2148" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000864" DisplayMethod="unsigned integer"/>
      <Element Offset="2160" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000870" DisplayMethod="hexadecimal"/>
      <Element Offset="2164" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000874" DisplayMethod="unsigned integer"/>
      <Element Offset="2176" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000880" DisplayMethod="hexadecimal"/>
      <Element Offset="2180" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000884" DisplayMethod="unsigned integer"/>
      <Element Offset="2192" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000890" DisplayMethod="hexadecimal"/>
      <Element Offset="2196" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000894" DisplayMethod="unsigned integer"/>
      <Element Offset="2208" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008A0" DisplayMethod="hexadecimal"/>
      <Element Offset="2212" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000008A4" DisplayMethod="unsigned integer"/>
      <Element Offset="2224" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008B0" DisplayMethod="hexadecimal"/>
      <Element Offset="2228" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000008B4" DisplayMethod="unsigned integer"/>
      <Element Offset="2240" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008C0" DisplayMethod="hexadecimal"/>
      <Element Offset="2244" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000008C4" DisplayMethod="unsigned integer"/>
      <Element Offset="2256" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008D0" DisplayMethod="hexadecimal"/>
      <Element Offset="2260" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000008D4" DisplayMethod="unsigned integer"/>
      <Element Offset="2272" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008E0" DisplayMethod="hexadecimal"/>
      <Element Offset="2276" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="000008E4" DisplayMethod="unsigned integer"/>
      <Element Offset="2288" Vartype="4 Bytes" Bytesize="4" OffsetHex="000008F0" DisplayMethod="hexadecimal"/>
      <Element Offset="2292" Vartype="4 Bytes" Bytesize="4" RLECount="67" OffsetHex="000008F4" DisplayMethod="unsigned integer"/>
      <Element Offset="2560" Vartype="Pointer" Bytesize="8" OffsetHex="00000A00" DisplayMethod="unsigned integer"/>
      <Element Offset="2568" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000A08" DisplayMethod="unsigned integer"/>
      <Element Offset="2576" Vartype="Pointer" Bytesize="8" OffsetHex="00000A10" DisplayMethod="unsigned integer"/>
      <Element Offset="2584" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000A18" DisplayMethod="unsigned integer"/>
      <Element Offset="2608" Vartype="Pointer" Bytesize="8" OffsetHex="00000A30" Description="Pointer to instance of CBodyComponentPoint" DisplayMethod="unsigned integer"/>
      <Element Offset="2616" Vartype="Pointer" Bytesize="8" OffsetHex="00000A38" DisplayMethod="unsigned integer"/>
      <Element Offset="2624" Vartype="4 Bytes" Bytesize="4" RLECount="73" OffsetHex="00000A40" DisplayMethod="unsigned integer"/>
      <Element Offset="2916" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000B64" DisplayMethod="hexadecimal"/>
      <Element Offset="2924" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000B6C" DisplayMethod="unsigned integer"/>
      <Element Offset="2936" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B78" DisplayMethod="hexadecimal"/>
      <Element Offset="2940" Vartype="4 Bytes" Bytesize="4" RLECount="3" OffsetHex="00000B7C" DisplayMethod="unsigned integer"/>
      <Element Offset="2952" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000B88" DisplayMethod="hexadecimal"/>
      <Element Offset="2956" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="00000B8C" DisplayMethod="unsigned integer"/>
      <Element Offset="2984" Vartype="Pointer" Bytesize="8" OffsetHex="00000BA8" Description="Pointer to instance of C_CSTeam" DisplayMethod="unsigned integer"/>
      <Element Offset="2992" Vartype="4 Bytes" Bytesize="4" RLECount="14" OffsetHex="00000BB0" DisplayMethod="unsigned integer"/>
      <Element Offset="3048" Vartype="Pointer" Bytesize="8" OffsetHex="00000BE8" DisplayMethod="unsigned integer"/>
      <Element Offset="3056" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000BF0" DisplayMethod="unsigned integer"/>
      <Element Offset="3104" Vartype="Float" Bytesize="4" OffsetHex="00000C20" DisplayMethod="unsigned integer"/>
      <Element Offset="3108" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000C24" DisplayMethod="unsigned integer"/>
      <Element Offset="3112" Vartype="Float" Bytesize="4" OffsetHex="00000C28" DisplayMethod="unsigned integer"/>
      <Element Offset="3116" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000C2C" DisplayMethod="unsigned integer"/>
      <Element Offset="3136" Vartype="Pointer" Bytesize="8" OffsetHex="00000C40" DisplayMethod="unsigned integer"/>
      <Element Offset="3144" Vartype="4 Bytes" Bytesize="4" RLECount="4" OffsetHex="00000C48" DisplayMethod="unsigned integer"/>
      <Element Offset="3160" Vartype="Pointer" Bytesize="8" OffsetHex="00000C58" DisplayMethod="unsigned integer"/>
      <Element Offset="3168" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000C60" DisplayMethod="unsigned integer"/>
      <Element Offset="3176" Vartype="Float" Bytesize="4" OffsetHex="00000C68" DisplayMethod="unsigned integer"/>
      <Element Offset="3180" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000C6C" DisplayMethod="unsigned integer"/>
      <Element Offset="3184" Vartype="Float" Bytesize="4" OffsetHex="00000C70" DisplayMethod="unsigned integer"/>
      <Element Offset="3188" Vartype="4 Bytes" Bytesize="4" RLECount="5" OffsetHex="00000C74" DisplayMethod="unsigned integer"/>
      <Element Offset="3208" Vartype="Pointer" Bytesize="8" OffsetHex="00000C88" DisplayMethod="unsigned integer"/>
      <Element Offset="3216" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000C90" DisplayMethod="unsigned integer"/>
      <Element Offset="3248" Vartype="Float" Bytesize="4" OffsetHex="00000CB0" DisplayMethod="unsigned integer"/>
      <Element Offset="3252" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000CB4" DisplayMethod="unsigned integer"/>
      <Element Offset="3256" Vartype="Float" Bytesize="4" OffsetHex="00000CB8" DisplayMethod="unsigned integer"/>
      <Element Offset="3260" Vartype="4 Bytes" Bytesize="4" RLECount="7" OffsetHex="00000CBC" DisplayMethod="unsigned integer"/>
      <Element Offset="3288" Vartype="Pointer" Bytesize="8" OffsetHex="00000CD8" DisplayMethod="unsigned integer"/>
      <Element Offset="3296" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000CE0" DisplayMethod="unsigned integer"/>
      <Element Offset="3304" Vartype="Pointer" Bytesize="8" OffsetHex="00000CE8" DisplayMethod="unsigned integer"/>
      <Element Offset="3312" Vartype="Pointer" Bytesize="8" OffsetHex="00000CF0" Description="Pointer to instance of C_CSTeam" DisplayMethod="unsigned integer"/>
      <Element Offset="3320" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000CF8" DisplayMethod="unsigned integer"/>
      <Element Offset="3344" Vartype="Pointer" Bytesize="8" OffsetHex="00000D10" Description="Pointer to instance of CBodyComponentPoint::NetworkVar_m_sceneNode" DisplayMethod="unsigned integer"/>
      <Element Offset="3352" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000D18" DisplayMethod="unsigned integer"/>
      <Element Offset="3400" Vartype="Float" Bytesize="4" OffsetHex="00000D48" DisplayMethod="unsigned integer"/>
      <Element Offset="3404" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000D4C" DisplayMethod="hexadecimal"/>
      <Element Offset="3408" Vartype="4 Bytes" Bytesize="4" RLECount="16" OffsetHex="00000D50" DisplayMethod="unsigned integer"/>
      <Element Offset="3472" Vartype="Pointer" Bytesize="8" OffsetHex="00000D90" DisplayMethod="unsigned integer"/>
      <Element Offset="3480" Vartype="4 Bytes" Bytesize="4" RLECount="6" OffsetHex="00000D98" DisplayMethod="unsigned integer"/>
      <Element Offset="3504" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DB0" DisplayMethod="hexadecimal"/>
      <Element Offset="3508" Vartype="4 Bytes" Bytesize="4" RLECount="12" OffsetHex="00000DB4" DisplayMethod="unsigned integer"/>
      <Element Offset="3556" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DE4" DisplayMethod="hexadecimal"/>
      <Element Offset="3560" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DE8" DisplayMethod="unsigned integer"/>
      <Element Offset="3564" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DEC" DisplayMethod="hexadecimal"/>
      <Element Offset="3568" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DF0" DisplayMethod="unsigned integer"/>
      <Element Offset="3572" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DF4" DisplayMethod="hexadecimal"/>
      <Element Offset="3576" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DF8" DisplayMethod="unsigned integer"/>
      <Element Offset="3580" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000DFC" DisplayMethod="hexadecimal"/>
      <Element Offset="3584" Vartype="Pointer" Bytesize="8" OffsetHex="00000E00" Description="Pointer to instance of CWrappedInterpolatedVarGuts&lt;CNetworkVelocityVector,1,CNetworkVelocityVector,0,CInterpolatedVar&lt;CNetworkVelocityVector&gt; &gt;" DisplayMethod="unsigned integer"/>
      <Element Offset="3592" Vartype="4 Bytes" Bytesize="4" RLECount="10" OffsetHex="00000E08" DisplayMethod="unsigned integer"/>
      <Element Offset="3632" Vartype="Double" Bytesize="8" OffsetHex="00000E30" DisplayMethod="unsigned integer"/>
      <Element Offset="3640" Vartype="Float" Bytesize="4" OffsetHex="00000E38" DisplayMethod="unsigned integer"/>
      <Element Offset="3644" Vartype="4 Bytes" Bytesize="4" RLECount="2" OffsetHex="00000E3C" DisplayMethod="unsigned integer"/>
      <Element Offset="3652" Vartype="4 Bytes" Bytesize="4" OffsetHex="00000E44" DisplayMethod="hexadecimal"/>
      <Element Offset="3656" Vartype="4 Bytes" Bytesize="4" RLECount="8" OffsetHex="00000E48" DisplayMethod="unsigned integer"/>
      <Element Offset="3688" Vartype="Pointer" Bytesize="8" OffsetHex="00000E68" Description="Pointer to instance of CParticleMgr" DisplayMethod="unsigned integer"/>
      <Element Offset="3696" Vartype="Pointer" Bytesize="8" OffsetHex="00000E70" Description="Pointer to instance of C_BaseEntityOuterHelper" DisplayMethod="unsigned integer"/>
      <Element Offset="3704" Vartype="4 Bytes" Bytesize="4" RLECount="63" OffsetHex="00000E78" DisplayMethod="unsigned integer"/>
      <Element Offset="3956" Vartype="String" Bytesize="11" OffsetHex="00000F74" DisplayMethod="unsigned integer"/>
      <Element Offset="3967" Vartype="Byte" Bytesize="1" OffsetHex="00000F7F" DisplayMethod="unsigned integer"/>
      <Element Offset="3968" Vartype="4 Bytes" Bytesize="4" RLECount="32" OffsetHex="00000F80" DisplayMethod="unsigned integer"/>
    </Elements>
  </Structure>
</Structures>